version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:v5.7-armhf-buster
    network_mode: 'host'
    environment:
      TZ: '{TIMEZONE}'
      WEBPASSWORD: '{WEB_PASSWORD}'
      ServerIP: '{SERVER_IP}'
      INTERFACE: {INTERFACE}
      DNSMASQ_LISTENING: {INTERFACE}
    tmpfs:
      - /tmp
      - /var/cache
      - /var/lib/php/sessions
    volumes:
      - './data/pihole:/etc/pihole'
      - './data/dnsmasq.d:/etc/dnsmasq.d'
    dns:
      - 127.0.0.1
      - 8.8.8.8
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - NET_RAW
    restart: unless-stopped
